default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

sqlite: &sqlite
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  primary:
    <<: *default
    database: store_development

  cache:
    <<: *sqlite
    database: store_development_cache.sqlite3
    migrations_paths: db/cache_migrate
  queue:
    <<: *sqlite
    database: store_development_queue.sqlite3
    migrations_paths: db/queue_migrate
  cable:
    <<: *sqlite
    database: store_development_cable.sqlite3
    migrations_paths: db/cable_migrate

test:
  <<: *default
  database: store_test

production:
  primary:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
    database: store_production
    username: store
    password: <%= ENV["STORE_DATABASE_PASSWORD"] %>
  cache:
    <<: *sqlite
    database: store_production_cache.sqlite3
    migrations_paths: db/cache_migrate
  queue:
    <<: *sqlite
    database: store_production_queue.sqlite3
    migrations_paths: db/queue_migrate
  cable:
    <<: *sqlite
    database: store_production_cable.sqlite3
    migrations_paths: db/cable_migrate
